name: Build DWM Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build DWM package
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:base-devel bash -c "
            pacman -Syu --noconfirm &&
            pacman -S --noconfirm libx11 libxft libxinerama imlib2 freetype2 git &&
            makepkg --syncdeps --noconfirm --cleanbuild
          "

      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: dwm-package
          path: '*.pkg.tar.zst'
