kname: Build DWM Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04  # You can change this based on your needs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to avoid shallow clone issues

      - name: Clean up Git configuration
        run: |
          # Remove any problematic extra headers or unwanted configurations
          git config --global --unset-all http.https://github.com/.extraheader || true
          git config --global --unset http.https://github.com/.extraheader || true
          git config --global --remove-section http.https://github.com || true
          git config --global --list  # Check the final git config for verification

      - name: Build DWM package in Arch Linux
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:base-devel bash -c "
            # Create a non-root user
            useradd -m builder &&
            passwd -d builder &&
            echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers &&
            
            # Fix permissions to allow builder user to write to /workspace
            chown -R builder:builder /workspace &&
            
            # Update system as root
            pacman -Syu --noconfirm &&
            pacman -S --noconfirm libx11 libxft libxinerama imlib2 freetype2 git &&
            
            # Build the package as a non-root user
            sudo -u builder bash -c '
              cd /workspace &&
              makepkg --syncdeps --noconfirm --cleanbuild
            '
          "

      - name: Upload package artifact
        uses: actions/upload-artifact@v4  # Update to v4
        with:
          name: dwm-package
          path: '*.pkg.tar.zst'

