name: Build DWM Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04  # Change this to ubuntu-24.04 when it's available

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get DWM Version and Release
        id: get_version
        run: |
          VERSION=$(grep 'pkgver=' PKGBUILD | cut -d'=' -f2)
          REL=$(grep 'pkgrel=' PKGBUILD | cut -d'=' -f2)
          echo "DWM version is $VERSION, release is $REL"
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=release::$REL"

      - name: Build DWM package in Arch Linux
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:base-devel bash -c "
            # Create a non-root user
            useradd -m builder &&
            passwd -d builder &&
            echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers &&

            # Fix permissions to allow builder user to write to /workspace
            chown -R builder:builder /workspace &&

            # Update system as root
            pacman -Syu --noconfirm &&
            pacman -S --noconfirm libx11 libxft libxinerama imlib2 freetype2 git &&

            # Build the package as a non-root user
            sudo -u builder bash -c '
              cd /workspace &&
              makepkg --syncdeps --noconfirm --cleanbuild
            '
          "

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: dwm-package-${{ steps.get_version.outputs.version }}-${{ steps.get_version.outputs.release }}  # Dynamic version and release from PKGBUILD
          path: '*.pkg.tar.zst'
