name: Build DWM Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04  # You can change this based on your needs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to avoid shallow clone issues

      - name: Get DWM Version and Release
        id: get_version
        run: |
          VERSION=$(grep 'pkgver=' PKGBUILD | cut -d'=' -f2)
          REL=$(grep 'pkgrel=' PKGBUILD | cut -d'=' -f2)
          echo "DWM version is $VERSION, release is $REL"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "RELEASE=$REL" >> $GITHUB_ENV

      - name: Build DWM package in Arch Linux
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:base-devel bash -c "
            # Create a non-root user
            useradd -m builder &&
            passwd -d builder &&
            echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers &&
            
            # Fix permissions to allow builder user to write to /workspace
            chown -R builder:builder /workspace &&
            
            # Update system as root
            pacman -Syu --noconfirm &&
            pacman -S --noconfirm libx11 libxft libxinerama imlib2 freetype2 git &&
            
            # Build the package as a non-root user
            sudo -u builder bash -c '
              cd /workspace &&
              makepkg --syncdeps --noconfirm --cleanbuild
            '
          "
      - name: Upload package artifact without zipping
        run: |
          # Find the package file by using the exact pattern
          PACKAGE_FILE=$(find $GITHUB_WORKSPACE -name "*.pkg.tar.zst")
          
          # Upload the package file directly (not zipped)
          echo "Uploading package: $PACKAGE_FILE"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -F "file=@$PACKAGE_FILE" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=$(basename $PACKAGE_FILE)"
