name: Build and Release DWM Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set GH_TOKEN for GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: echo "GH_TOKEN is set."

      - name: Get DWM Version and Release
        id: get_version
        run: |
          VERSION=$(grep 'pkgver=' PKGBUILD | cut -d'=' -f2)
          RELEASE=$(grep 'pkgrel=' PKGBUILD | cut -d'=' -f2)
          echo "DWM version is $VERSION, release is $RELEASE"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
        env:
          GITHUB_ENV: $GITHUB_ENV
          
      - name: Build DWM package in Arch Linux
        env:
          VERSION: ${{ env.VERSION }}
          RELEASE: ${{ env.RELEASE }}
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:base-devel bash -c "
            set -e
            useradd -m builder &&
            passwd -d builder &&
            echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers &&
            chown -R builder:builder /workspace &&
            pacman -Syu --noconfirm &&
            pacman -S --noconfirm libx11 libxft libxinerama imlib2 freetype2 git &&
            sudo -u builder bash -c '
              cd /workspace &&
              makepkg --syncdeps --noconfirm --cleanbuild
            '
          "

      - name: Delete Old Release (if Exists)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          VERSION: ${{ env.VERSION }}
          RELEASE: ${{ env.RELEASE }}
        run: |
          VERSION_TAG="v${{ env.VERSION }}-${{ env.RELEASE }}"
          EXISTING_RELEASE="DWM ${VERSION_TAG} Release"
          if [ -n "$EXISTING_RELEASE" ]; then
            echo "Deleting existing release: $EXISTING_RELEASE"
            gh release delete "$EXISTING_RELEASE" --yes
            git tag -d "$VERSION_TAG"
            git push --delete origin "$VERSION_TAG"
          fi
          
      - name: Create a New Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          VERSION: ${{ env.VERSION }}
          RELEASE: ${{ env.RELEASE }}
        run: |
          VERSION_TAG="v${{ env.VERSION }}-${{ env.RELEASE }}"
          PACKAGE_FILE=$(find $GITHUB_WORKSPACE -name "*.pkg.tar.zst" | head -n 1)
          echo "Creating release: $VERSION_TAG"
          
          gh release create "$VERSION_TAG" "$PACKAGE_FILE" \
            --title "DWM $VERSION_TAG Release" \
            --notes "## Release Notes
      
          - New features and improvements
          - Fixed minor bugs"
